version: "3"

services:
  marketplace:
    image: marketplace:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - marketplace-db

  marketplace-db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
